### ISSUE TITLE
ToString com texto errado no Disco

### ISSUE THREAD

**Issue by WilliamMN** [Britooo/looca-api#4]
str.append("\nNome: %s\n");
        str.append("Modelo: %s\n");
        str.append("Serial: %s\n");
        str.append("Tamanho: %s\n");
        str.append("Leituras: %s\n");
        str.append("BYtes de leitura: %s\n");
        str.append("Escritas: %s\n");
        str.append("Bytes de escritas: %s\n"); <----- AQUI
        str.append("Tamanho atual da fila: %s\n");
        str.append("Tempo de transferência: %s\n");

**Comment by Britooo** [comment]
Resolvido.
